### ISSUE TITLE
`module.exports = { a, b, ... }` may be able to be converted to `export { a, b, ... }`

### ISSUE THREAD

**Issue by hata6502** [azu/commonjs-to-es-module-codemod#4]
`module.exports = { a, b, ... }` may be able to be converted to ESM named export.

Input
```js
module.exports = { a, b, ... }
```

Current output
```js
export default { a, b, ... }
```

Recommended output
```js
export { a, b, ... }
```

**Comment by azu** [comment]
It is good if the file has only `export default`.

```js
export default { a, b, ... }
```

However, the transform will be wrong if the file has named export and default export.

```js
const a = 1, b = 2, c = 3;
module.exports.c = c;
module.exports = { a, b };
```

are different  means with

```js
const a = 1, b = 2, c = 3;
export { c };
export { a, b };
```

**Comment by hata6502** [comment]
Thank you for your reply!

```js
const a = 1, b = 2, c = 3;
export { c };
export { a, b };
```

is wrong output.
But the input

```js
const a = 1, b = 2, c = 3;
module.exports.c = c;
module.exports = { a, b };
```

also seems invalid because the default export `c` is overwritten with `{a, b}`.

The correct input to use both of named export and default export:

```js
const a = 1, b = 2, c = 3;
module.exports = { default: c, a, b};
```

https://www.bignerdranch.com/blog/default-exports-or-named-exports-why-not-both/

**Comment by hata6502** [comment]
```js
module.exports = { a: 1 };
```

can't be converted to

```js
export { a: 1 }  // Syntax error
```

**Comment by hata6502** [comment]
This proposal seems difficult to implement...

**Comment by hata6502** [comment]
**This proposal can't be implemented.**
Because it can't be detected which to use `named export` or `default export`.

Input:

```js
module.exports = { a };

const { a } = require('...');  // OK
const foo = require('...');  // OK
```

Output as named export
```js
export { a };

import { a } from '...';  // OK
import foo from '...';  // NG
```

Output as default export
```js
export default { a };

import { a } from '...';  // NG
import foo from '...';  // OK
```
